In [35]:
import numpy as np

In [36]:
data=np.load("data/mm-fit/w00/w00_pose_2d.npy")

In [41]:
print(data)

[[[ 4050.      817.413   795.951 ...   825.284   776.276   837.118]
  [ 4051.      817.449   797.849 ...   825.316   776.287   838.924]
  [ 4052.      817.449   797.897 ...   825.319   776.335   838.955]
  ...
  [67965.      615.658   635.335 ...   619.697   631.279   648.888]
  [67966.      615.658   635.332 ...   619.698   631.279   648.888]
  [67967.      615.663   635.332 ...   621.504   631.279   648.886]]

 [[ 4050.      343.362   394.275 ...   333.469   331.593   335.443]
  [ 4051.      357.077   404.093 ...   345.294   343.328   347.286]
  [ 4052.      368.895   415.926 ...   355.179   357.045   360.971]
  ...
  [67965.      210.128   251.235 ...   196.39    196.469   194.437]
  [67966.      210.103   251.237 ...   196.367   196.469   194.437]
  [67967.      210.103   251.237 ...   196.359   196.469   194.431]]]


In [30]:
print(data.shape)

(2, 63918, 19)


In [31]:
data = data.transpose(1,0,2)
data.shape

(63918, 2, 19)

In [32]:
data = data.reshape(-1,38)
data.shape

(63918, 38)